server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/qg_qianhou?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
#    type: com.alibaba.druid.pool.DruidDataSource
#  servlet:
#    multipart:
#      maxFileSize: 100MB
#      maxRequestSize: 100MB
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#
#logging:
#  level:
#    com:
#      example:
#        mapper:
#          debug